apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-aplu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-aplu
    app.kubernetes.io/part-of: devfile-sample-python-basic
  name: devfile-sample-python-basic-aplu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-aplu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-aplu
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/mkovarik-tenant/devfile-sample-python-basic/devfile-sample-python-basic-aplu@sha256:bebbf973e872f8a945180d111f319f3e92388f44aac8e738c56542e0a56a8950
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
