apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-aplu
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/mkovarik-tenant/devfile-sample-python-basic/devfile-sample-python-basic-aplu@sha256:bebbf973e872f8a945180d111f319f3e92388f44aac8e738c56542e0a56a8950
        name: my-python
        resources: {}
status: {}
